AFM-SPM/AFMReader

COPYING, README.md, examples/example_01.ipynb, tests/test_asd.py, topofileformats/__init__.py, topofileformats/asd.py, topofileformats/io.py
=> Apply linting and formatting to codebase

.github/workflows/tests.yaml, .gitignore, pyproject.toml
Closes #7
Configured to use CodeCov in reporting.
Also ignores Emacs temporary files.
=> Adds workflow to run tests

CODE_OF_CONDUCT.md, README.md, topofileformats/asd.py
Closes #14
+ Adds `CODE_OF_CONDUCT.md`.
+ Adds supported file formats and intended work to `README.md`.
+ Adds basic instructions on contributing to `README.md`.
=> Adds code of conduct for contributing; expands README.md

.pre-commit-config.yaml
+ `debug-statements` - Checks for debug statements before commits.
+ `no-commit-to-branch` - Prevents commits being made to specific branches (`main` and `master` by default).
=> Adds some useful pre-commit/pre-commit-hooks

.gitignore, pyproject.toml, topofileformats/__init__.py
=> Switches to dynamic versioning with setuptools_scm

README.md, tests/test_asd.py
I discovered [`pytest.param()`](https://docs.pytest.org/en/7.1.x/reference/reference.html?#pytest.param) which allows parameter sets to be given `ids` and thought it a simple but useful habit to start using.
Another useful option is the `marks=` so particular parameters can be marked to fail, or be skipped if certain conditions are met, but these aren't needed here.
=> Adds ids to tests via pytest.param

.gitignore, examples/example_01.ipynb, pyproject.toml, tests/test_asd.py, topofileformats/__init__.py, topofileformats/asd.py, topofileformats/logging.py
Closes #2 
This PR replaces all the `print` statements with logging from `loguru` (colour coded too)
=> Replace print with loguru

pyproject.toml
Noticed that we hadn't configured test coverage to exclude the `tests/` directory so have added this to `pyproject.toml`.
=> Configuring test coverage

.git-blame-ignore-revs, .pre-commit-config.yaml, pyproject.toml, topofileformats/asd.py, topofileformats/io.py
Closes #39
+ Adds the `numpydoc-validation` pre-commit hook.
+ Tidies up all docstrings in current codebase (may want to revisit those in pending PRs #33, #34 and #36).
+ Ignores commit where changes to docstrings are made.
+ Updates configuration of `ruff` in `pyproject.toml`.
=> ci: Adds numpydoc-validation to pre-commit hooks

.github/workflows/tests.yaml, pyproject.toml
Closes #47
Closes #48
+ Bumps minimum version to Python 3.9
+ Splits optional dependencies
=> chore: Minimum Python 3.9; Splits optional dependencies

.github/workflows/pypi.yaml
+ Adds `.github/workflows.pypi.yaml` to automate publishing of commits tagged with `v*` to PyPI.
+ Need to build locally and publish manually to setup account first and generate a token for the `topostats@shseffield.ac.uk` account.
=> ci: Add pypi.yaml to automate publishing to PyPI

pyproject.toml
Extra dependency `setuptools_scm[toml]` under `pypi` had a tpyo in it which prevented installing the required packages for building and publishing.
=> ci: Correcting tpyo in dependency

.github/workflows/pypi.yaml, .gitignore
Job [failed](https://github.com/AFM-SPM/AFMReader/actions/runs/9284848123) so updating permissions to grant permissions.
Also ignores `tmp/` directory within repository.
=> ci: Adding permissions for token

README.md
Was notified of [howfairis](https://github.com/fair-software/howfairis) repository checker by @tdjames1 so ran it against the repository and am adding the badge provided.
=> chore: Adds fair-software.eu badge to README.md

pyproject.toml
The `pyproject.toml` was missing a `[tool.setuptools.packages.find]` section which meant that on trying to install
locally it for some reason tried to include a `tmp/` directory (something I often create within projects for tasks that
need undertaking but is explicitly excluded from Git via `.gitignore`) and I observed the following complaint from `pip`
```
❱ pip install -e .
Obtaining file:///home/neil/work/git/hub/AFM-SPM/AFMReader
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... error
error: subprocess-exited-with-error
× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
error: Multiple top-level packages discovered in a flat-layout: ['tmp', …
```
=> chore: Explicitly define where package files reside

AFMReader/spm.py
Closes #83 
Adds the same units dictionary that was used in TopoStats to AFMReader. Apologies, I somehow omitted the units `pm` and `mm` from when I copied the code over.
=> Fix: units pm and mm missing from spm_pixel_to_nm_scaling

.gitignore, .pre-commit-config.yaml, pyproject.toml
Closes #88
Also adds a few more things to `.gitignore`.
=> ci: Adds pytest-testmon to local pre-commit hooks

.pre-commit-config.yaml, .pylintrc, AFMReader/asd.py, AFMReader/gwy.py, AFMReader/io.py, tests/test_asd.py, tests/test_gwy.py, tests/test_ibw.py, tests/test_io.py, tests/test_jpk.py, tests/test_spm.py, tests/test_topostats.py
Closes #96
Adds [mypy](https://mypy.readthedocs.io/) checks to [pre-commit](https://pre-commit.com) hooks.
Used [RightTyper](https://github.com/RightTyper/RightTyper) to help identify errors and the correct types, it was useful but not comprehensive as mypy still threw a lot of problems which have, mostly, been corrected. This was mainly as a precurrsor to addressing and correcting type hints in TopoStats.
There were a few areas where ignores have been added as I couldn't see how to correct these. They may want correcting in the modules, less important for the tests.
=> Add mypy to pre-commit and improve typehints

pyproject.toml
Closes #101
Also improved the format/structure of linting configuration under `ruff`.
=> style: Disable ruff A005 (stdlib-module-shadowing)

.github/workflows/build_mkdocs.yaml, .pre-commit-config.yaml, .prettierignore, docs/api.md, docs/api/asd.md, docs/api/gwy.md, docs/api/ibw.md, docs/api/io.md, docs/api/jpk.md, docs/api/logging.md, docs/api/spm.md, docs/api/topostats.md, docs/contributing.md, docs/index.md, docs/installation.md, docs/introduction.md, docs/links.md, docs/usage.md, docs/workflow.md, mkdocs.yml, pyproject.toml
I had an hour of work left and was unlikely to be able to concentrate deeply on work so used the time productively to
knock up the documentation for AFMReader using [mkdocs](https://www.mkdocs.org/).
Its pretty basic but once merged pushes to the `main` branch of files under `docs/` will trigger the documentation to be
rebuilt. It includes the API docs auto-generated from docstrings and the ability to easily switch between versions.
This is a prelude to switching TopoStats and [AFM-SPM.github.io](https://github.com/AFM-SPM/AFM-SPM.github.io) over to
`mkdocs`.
If you want to test it out locally to see what it looks like...
``` shell
git pull
git switch ns-rse/mkdocs-website
pip install -e .[docs]
mkdocs serve
```
...and check the output for the URL to view the site at locally.
=> docs: Adds basic documentation using mkdocs

.pre-commit-config.yaml, AFMReader/asd.py, AFMReader/ibw.py, tests/test_asd.py, tests/test_gwy.py, tests/test_ibw.py, tests/test_jpk.py, tests/test_spm.py, tests/test_topostats.py
Closes #80
- Ensures `FileNotFound` error is consistently raised across modules.
- Adds a test for each module that `FileNotFound` error is raised.
- Standardises importing of module rather than functions across all tests.
=> tests: FileNotFound consistently raised & tested

AFMReader/topostats.py, tests/test_topostats.py
Closes #109
Rather than return the HDF5 object loaded from `.topostats` as a dictionary as the third item in a tuple along with the
`image` and `pixel_to_nm_scaling` (both of which are extracted from the loaded data anyway) just the dictionary is
returned. This matches the structure of objects created by TopoStats and how they are saved to HDF5 files.
=> feature: Returns just dictionary when loading .topostats

AFMReader/jpk.py, examples/example_01.ipynb, tests/test_jpk.py
As described in issue #116, currently the data (z values) scaling factors used for most channels in JPK images are incorrect and some channels cannot be read.
This pull request creates the fucntion `_get_z_scaling()` that extracts the correct scaling factor for each channel and uses these to scale the image.
Additonally corrects a typo in the example notebook.
This fixes #116
=> Scaling JPK data values correctly

AFMReader/default_config.yaml, AFMReader/io.py, AFMReader/jpk.py, docs/usage.md, pyproject.toml, tests/resources/test.yaml, tests/test_io.py
Off the back of #118 (thanks @derollins) I've parameterised the JPK tags that were introduced into
`AFMReader/default_config.yaml` and load these by default when using `AFMReader.load_jpk()`. A parameter is introduced
to that function (`confi_path`) which allows users to specify their own configuration file should they wish to use alternative tags.
- Copies the `read_yaml()` function and tests from TopoStats.
- Brief description of configuration file and structure added to `docs/usage.md` (where some tables were also aligned by
Emacs).
Exiting `tests/test_jpk.py` pass.
I envisage this being an extensible and flexible way of users being able to handle parameters changing the array of file types that 
exist now and in the future and it should be easy to extend to other file formats.
=> feature: introduce config file for JPK tags

AFMReader/topostats.py
Compares versions of `.topostats` as strings with a view to moving to storing the version of TopoStats that `.topostats` files were created in as a field in the HDF5 `.topostats` file itself.
Strings seem to be compared logically...
```python
In [1]import topostats
In [2]: topostats.__release__
Out[2]: '2.3.2'
In [3]: topostats.__release__ > "0.2"
Out[3]: True
In [4]: "0.2.1" > "0.2"
Out[4]: True
In [5]: "0.2.0" >= "0.2"
Out[5]: True
```
=> tests(topostats): Compare versions as strings

pyproject.toml, tests/conftest.py
Further to [previous review](https://github.com/AFM-SPM/AFMReader/pull/131#discussion_r2044558273) this replaces the redefinitions of `caplog` with the [pytest-loguru extension](https://github.com/mcarans/pytest-loguru).
=> tests: Adds pytest-loguru to test dependencies

tests/test_topostats.py
We are going to switch from having the `topostats_file_version` as the name for the metadata that `.topostats` files
were generated with to using the `topostats_version` as key which will align with the release tag and make it easier for
work to be reproducible.
This small commit adds the `version_key` variable to the `tests/test_topostats.py::test_load_topostats()` test so that
the key against which tests are made will work with old versions and future versions.
=> tests: make topostats tests flexible to key name

AFMReader/asd.py, AFMReader/general_loader.py, AFMReader/gwy.py, AFMReader/ibw.py, AFMReader/jpk.py, AFMReader/topostats.py, tests/test_general_loader.py
This PR adds a general file loader into ~TopoStats~ AFMReader which handles any filepath and uses the file extention to ship it to the correct reader.
This does include a few funky additions changes:
- The general loader takes a filepath and channel string, and returns a tuple of `(image, px2nm)`.
- As this is made for the Napari plugin we are developing, it needs to "pass along" the error messages to Napari, thus the channel errors are poorly handled by being returned as a tuple of `(ValueError(<message>), None)`.
- For `.topostats` files, it uses the channel input to identify any image keys ("image" and "image_original" from the file). These are also returned for the error message.
- Functions, linting and tests are all there :)
=> Add general loader module

pyproject.toml
I found that for some reason an old version of `pySPM-0.2.23` was pulled in which caused errors as it used deprecated
SciPy libraries (see [closed issue](https://github.com/scholi/pySPM/issues/53)). Its not clear from the
[log](https://productionresultssa1.blob.core.windows.net/actions-results/fa03bab8-0e33-47bc-a2e8-78ec876aa492/workflow-job-run-ea76b43c-ee68-5caa-254f-051e5a73daf3/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-05-15T16%3A10%3A40Z&sig=mocjmoixOhWCRWmd3Vjxtws1iftIh6IBXpAd8s14VmQ%3D&ske=2025-05-16T00%3A42%3A37Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-05-15T12%3A42%3A37Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-05-15T16%3A00%3A35Z&sv=2025-05-05)
why this old version was selected either.
Have therefore pinned …
=> packaging: Set pySPM min version to 0.6.2

pyproject.toml
Stupidly forgot its the [AFM-SPM/pySPM fork](https://github.com/AFM-SPM/pySPM/) where I've bumped the Numpy version to be `^2.0.0` and not simply pinning pySPM~=0.6.2 that is required.  Rushing and being distracted not helpful!
=> setup: Use AFM-SPM/pySPM fork

pyproject.toml
[pySPM-0.6.3](https://pypi.org/project/pyspm/0.6.3/) has been released to PyPI and incorporates support for Numpy
2.0 (which was the reason for switching to the AFM-SPM/pySPM fork).
Reverting back which means we will be able to make a new release of AFMReader so that @MaxGamill-Sheffield can update
the `napari-afmreader` package to rely on the PyPI version of AFMReader.
=> chore: Revert pySPM to install from PyPI
